# Generated by Django 4.2.5 on 2023-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_obj', models.FileField(upload_to='models/obj/')),
                ('model_json', models.FileField(blank=True, null=True, upload_to='models/json/')),
            ],
        ),
    ]
