# Generated by Django 4.2.5 on 2023-11-17 14:30

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_3d', models.FileField(upload_to=main.models.custom_upload_to)),
                ('size_x', models.FloatField()),
                ('size_y', models.FloatField()),
                ('size_z', models.FloatField()),
                ('custom_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_json_filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
