# Generated by Django 4.2.5 on 2023-10-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadedobjects", name="file",),
        migrations.AddField(
            model_name="uploadedobjects",
            name="image",
            field=models.ImageField(default=1, upload_to="upload_objects/"),
            preserve_default=False,
        ),
    ]
